name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version

    - name: Deploy Bicep template
      run: |
        az deployment group create --resource-group <resource-group-name> --template-file ./infra.bicep

    - name: Deploy Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: <function-app-name>
        package: ./shipper
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}

    # Deploying Power BI reports via GitHub Actions is currently not supported.
    # You can manually upload the Power BI report file to the Power BI service as described in your README.